version: '3'

services:
  app:
    tty: true
    container_name: noveland-app-server
    image: noveland-app:0.0.1
    build:
      context: .
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/home/app
      - /home/app/node_modules
      - /home/app/config
      - ./models:/home/app/models
