version: '3'

services:
  app:
    tty: true
    container_name: noveland-app-server
    image: noveland-app:0.0.1
    build:
      context: .
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/home/app
      - /home/app/node_modules
      - /home/app/config
      - ./models:/home/app/models
      
  nginx:
    container_name: nginx-server
    build: ./nginx
    image: nginx-server:1.0.0
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
