
name: CD to EC2

on:
  push:
    branches: [master]
    
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: [self-hosted, label-development]
    steps:
      - name: user check
        run: whoami
      - name: checkout source code
        uses: actions/checkout@v2
      - name: make .env
        run: |
          touch .env
          echo DB_PROD_USERNAME = ${{ secrets.DB_PROD_USERNAME }} >> .env
          echo DB_PROD_PASSWORD = ${{ secrets.DB_PROD_PASSWORD }} >> .env
          echo DB_PROD_HOST = ${{ secrets.DB_PROD_HOST }} >> .env
          echo JWT_SECRET_KEY  = ${{ secrets.JWT_SECRET_KEY  }} >> .env
          echo GOOGLE_CLIENT_ID   = ${{ secrets.GOOGLE_CLIENT_ID   }} >> .env
          echo GOOGLE_CLIENT_SECRET   = ${{ secrets.GOOGLE_CLIENT_SECRET   }} >> .env
          
      - name: Docker build and run
        run: |
          docker-compose up -d --build
        
