name: docker-cd

on:
  push:
    branches: [ master ]
    
jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Deploy to EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/noveland_server/back-end"
          
      - name: 'Create env file'
        run: |
          touch .env
          echo DB_PROD_USERNAME = ${{ secrets.DB_PROD_USERNAME }} >> .env
          echo DB_PROD_PASSWORD = ${{ secrets.DB_PROD_PASSWORD }} >> .env
          echo DB_PROD_HOST = ${{ secrets.DB_PROD_HOST }} >> .env
          echo JWT_SECRET_KEY  = ${{ secrets.JWT_SECRET_KEY  }} >> .env
          echo GOOGLE_CLIENT_ID   = ${{ secrets.GOOGLE_CLIENT_ID   }} >> .env
          echo GOOGLE_CLIENT_SECRET   = ${{ secrets.GOOGLE_CLIENT_SECRET   }} >> .env
        
      - name: Build docker image and run containers
        run: docker-compose up -d --build
    
        
     
