
name: CD to EC2

on:
  push:
    branches: [master]
    
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: [self-hosted, label-development]
    steps:
      - name: checkout source code
        uses: actions/checkout@v2
      
      - name: Docker build and run
        run: |
          docker-compose up -d --build
        
